### ISSUE TITLE
ocamllex always fails on java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by xavierleroy** [xclerc/ocamljava#18]
All invocations of ocamllex (the one packaged with ocamljava) fail when generating the .ml file.  (My configuration: openjdk-7 on Linux).

Repro case:

$ echo 'rule main = parse "" { () }' > foo.mll
$ ocamllex foo.mll
1 states, 0 transitions, table size 6 bytes
Fatal error: exception Sys_error("java.nio.channels.ClosedChannelException")

**Comment by xclerc** [comment]
For the record, the problem is related to the ocamljar
tool (that is applied to binaries of the binary distribution).
