### ISSUE TITLE
ocamljava fatal error "exception Not_found"

### ISSUE THREAD

**Issue by xavierleroy** [xclerc/ocamljava#19]
"make" of the attached repro case aborts with

ocamljava -c Parser.ml
Fatal error: exception Not_found

I did not have the fortitude to build a smaller repro case.

**Comment by xavierleroy** [comment]
On Xavier Clerc's advice, I tried with the OPAM version of ocamljava (instead of the binary distribution), and I'm sorry to report that the problem is here in this other version as well:

$ ocamljava -c Parser.ml
Fatal error: exception Not_found
(Cannot print stack backtrace: program not linked with -g)
$ type ocamljava
ocamljava is hashed (/home/xleroy/.opam/ocamljava-2.0-alpha2/bin/ocamljava)

**Comment by xclerc** [comment]
For the record, the problem is related to the `ocamljar`
tool (that is applied to binaries of the binary distribution).
